### ISSUE TITLE
Possibly inaccurate `LogRecord.created` value when the log call isn't immediately awaited

### ISSUE THREAD

**Issue by hamstap85** [b2wdigital/aiologger#104]
Because `aiologger.logger.Logger._log` is a coroutine, it is possible for the log task to be queued for much later, if one does not immediately await, e.g. `logger.info('a message')` vs `await logger.info('a message')`.

Since nothing in this function is a coroutine until the call to `await self.handle(record)`, I suggest that this is where the task is returned. I will submit a pull request to demonstrate this.

**Comment by hamstap85** [comment]
Pull request created at https://github.com/b2wdigital/aiologger/pull/105

**Comment by daltonmatos** [comment]
Closed by #105.

Thanks @hamstap85. :tada:
