### ISSUE TITLE
"loop" argument of Lock() Deprecated

### ISSUE THREAD

**Issue by TensorTom** [b2wdigital/aiologger#108]
aiologger\handlers\streams.py:37: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  `self._initialization_lock = asyncio.Lock(loop=self.loop)`

**Comment by diogommartins** [comment]
Hi @TensorTom , thanks a lot for noticing it! Are you willing to submit a pull request with the changes? We would gladly review and merge it

**Comment by graingert** [comment]
it's also deprecated pretty much everywhere else - eg asyncio.gather

**Comment by graingert** [comment]
it's probably a good idea to remove the loop arg from the log handler etc also
