### ISSUE TITLE
Rename THUERDAYS to THURSDAYS

### ISSUE THREAD

**Issue by aalex** [b2wdigital/aiologger#126]
I believe there is a typo error in the THUERDAYS constant.

In aiologger.files.AsyncTimeRotatingFileHandler

**Comment by daltonmatos** [comment]
Good catch! Thanks @aalex !

It's here: https://github.com/b2wdigital/aiologger/blob/master/aiologger/handlers/files.py#L174

Would you open a Pull request to fix it? With all tests passing it's ok to merge.

Thanks.

**Comment by aalex** [comment]
Yes. There you go.
