### ISSUE TITLE
Cyrillic and UTF-8

### ISSUE THREAD

**Issue by rsaleev** [b2wdigital/aiologger#94]
I have a problem with writing to file records with cyrillic symbols, even with pre-defined encoding
`{"logged_at": "2019-11-26T15:51:23.655266+03:00", "level": "DEBUG", "msg": "\u0422\u0435\u0441\u0442\u043e\u0432\u043e\u0435 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 UTF-8"}`

It happens only with `JsonLogger` instance even wih default handlers.

 ```    
        logger = JsonLogger()
        logger.name = __name__
        handler = AsyncTimedRotatingFileHandler(
            filename=log_file,
            encoding='utf-8',
            when=RolloverInterval.DAYS,
            interval=1,
            backup_count=31
        )
```

**Comment by daltonmatos** [comment]
Hello @rsaleev,

could you demonstrate the correct behavior using a ipython session? Maybe this could be the start of the investigation on why `JsonLogger` is not doind what it should.

Thanks,

**Comment by rsaleev** [comment]
> Hello @rsaleev,
> 
> could you demonstrate the correct behavior using a ipython session? Maybe this could be the start of the investigation on why `JsonLogger` is not doind what it should.
> 
> Thanks,

Sorry for late answer. 
`logger = JsonLogger(serializer_kwargs={'ensure_ascii': False})` solved my problem.
